# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Devhub API

on:
  push:
    branches: [ main, staging ]
    tags: v*
  pull_request:
    branches: [ staging ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
  
  deploy:
    runs-on: macos-latest
    needs: run-test
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        dir: [devhub-media-content-service]
        include:
        #- dir: devhub-api
        #  prod: devhub-api-nnbxy
        #  staging: devhub-api-staging-oqtmn
        #- dir: devhub-catalogue-export
        #  prod: devhub-catalogue-export-bafwl
        #  staging: devhub-catalogue-export-staging-waduq
        #- dir: devhub-search-service
        #  prod: devhub-search-service-elepi
        #  staging: devhub-search-service-staging-qrtnp
        - dir: devhub-media-content-service
          prod: devhub-media-content-service-dpbne
          staging: devhub-media-content-service-glhzl
    steps:
    - uses: actions/checkout@v2
    - name: "Install the Realm CLI"
      run: |
          npm install -g mongodb-realm-cli
    
    - name: "Authenticate and Push staging app"
      if: ${{ github.ref == 'refs/heads/staging' }} # Merging to the staging branch
      run: |
          realm-cli login --api-key="${{ secrets.REALM_STAGING_API_PUBLIC_KEY }}" --private-api-key="${{ secrets.REALM_STAGING_API_PRIVATE_KEY }}"
          cd ${{ matrix.dir }}
          sed -i '' 's/"app_id": ".*"/"app_id": "${{ matrix.staging }}"/' realm_config.json
          realm-cli push --remote="${{ matrix.staging }}" -y

    - name: "Authenticate and Push prod app"
      if: ${{ github.ref == 'refs/heads/main' }} # Merging to the main branch
      run: |
          realm-cli login --api-key="${{ secrets.REALM_PROD_API_PUBLIC_KEY }}" --private-api-key="${{ secrets.REALM_PROD_API_PRIVATE_KEY }}"
          cd ${{ matrix.dir }}
          sed -i '' 's/"app_id": ".*"/"app_id": "${{ matrix.prod }}"/' realm_config.json
          realm-cli push --remote="${{ matrix.prod }}" -y